name: Build and Deploy

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  

    steps:
      # 1. 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 安装 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. 安装依赖并构建前端（例如 npm 项目）
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # 4. 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t manyaking/my_docker_hub:$IMAGE_TAG .
          docker tag manyaking/my_docker_hub:$IMAGE_TAG manyaking/my_docker_hub:latest

      # 5. 登录 Docker Hub 并推送镜像（可选）
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker push manyaking/my_docker_hub:$IMAGE_TAG
          docker push manyaking/my_docker_hub:latest