name: Build and Deploy

on:
  push:
    branches:
      - master  # 当代码推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 托管的运行器

    steps:
      # 1. 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 安装依赖并构建前端（例如 npm 项目）
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # 3. 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t manyaking/my_docker_hub:latest .

      # 4. 登录 Docker Hub 并推送镜像（可选）
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ manyaking }}
          password: ${{ dckr_pat_23xS5TH0Xxsc8RRZ5hMvg_ej64Y }}

      - name: Push Docker Image
        run: |
          docker push manyaking/my_docker_hub:latest
